/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_parqueadero;

import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author rojas
 */
public class editar_cliente extends javax.swing.JFrame {

    /**
     * Creates new form editar_cliente
     */
    Registro registro;
    admindentro admin;
    String  IND_NR=" ";
    public editar_cliente(Registro registro1) {
        initComponents();
        registro=registro1;
    }
public void resibir(admindentro admin1){
        admin=admin1;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        tx_residencia = new javax.swing.JTextField();
        tx_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tx_placa = new javax.swing.JTextField();
        tx_modelo = new javax.swing.JTextField();
        tx_marca = new javax.swing.JTextField();
        bn_buscarcliente = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        tx_celular = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bn_editarcliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(627, 440));
        setMinimumSize(new java.awt.Dimension(627, 440));
        setPreferredSize(new java.awt.Dimension(627, 440));
        getContentPane().setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("buscar cliente por la cedula ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 100, 210, 20);
        getContentPane().add(tx_residencia);
        tx_residencia.setBounds(150, 300, 100, 20);

        tx_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(tx_nombre);
        tx_nombre.setBounds(160, 270, 170, 20);

        jLabel5.setBackground(new java.awt.Color(255, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre Completo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 260, 150, 30);

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Residencia");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 290, 110, 30);

        jLabel11.setBackground(new java.awt.Color(255, 0, 0));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Numero celular");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 320, 130, 30);

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("modelo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 300, 100, 20);

        jLabel8.setBackground(new java.awt.Color(255, 0, 0));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("placa");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 330, 90, 20);

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("marca ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(430, 280, 90, 20);

        jLabel10.setBackground(new java.awt.Color(0, 0, 204));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Informacion del auto");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(450, 240, 160, 40);
        getContentPane().add(tx_placa);
        tx_placa.setBounds(320, 340, 100, 20);
        getContentPane().add(tx_modelo);
        tx_modelo.setBounds(330, 300, 100, 20);

        tx_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_marcaActionPerformed(evt);
            }
        });
        getContentPane().add(tx_marca);
        tx_marca.setBounds(480, 280, 100, 20);

        bn_buscarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarClienteIcon.jpg"))); // NOI18N
        bn_buscarcliente.setText("buscar");
        bn_buscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_buscarclienteActionPerformed(evt);
            }
        });
        getContentPane().add(bn_buscarcliente);
        bn_buscarcliente.setBounds(360, 90, 130, 60);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "automovil", "motocicleta", "cicla" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(480, 310, 100, 20);
        getContentPane().add(tx_celular);
        tx_celular.setBounds(150, 330, 100, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(250, 100, 90, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Parking_Logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 0, 290, 89);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Business-Restaurant.png"))); // NOI18N
        jLabel3.setText("Bienvenido  administrador");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 400, 90);

        bn_editarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/images.jpg"))); // NOI18N
        bn_editarcliente.setText("editar cliente");
        bn_editarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_editarclienteActionPerformed(evt);
            }
        });
        getContentPane().add(bn_editarcliente);
        bn_editarcliente.setBounds(430, 340, 160, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/articulo-parqueadero.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bn_editarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_editarclienteActionPerformed
           String sPlaca = tx_placa.getText();     
           String sNombre =tx_nombre.getText();
           String srecidencia =tx_residencia.getText();
           String scelular =tx_celular.getText();
           String smarca =tx_marca.getText();
           String smodelo =tx_modelo.getText();
           
           String qrq ="update registro set (placa, nombre_completo, residencia, num_celular, modelo, marca ) values ('"+sPlaca+"','"+sNombre+"','"+srecidencia+"',"+scelular+",'"+smodelo+"','"+smarca+"')";
        
        try{
               
               registro.eliminar(qrq);
               JOptionPane.showMessageDialog(null, "Registro grabado satisfactoriamente");
               admin.setVisible(true);
               this.dispose();
                tx_nombre.setText(IND_NR);
                tx_residencia.setText(IND_NR);
                tx_celular.setText(IND_NR);
                tx_marca.setText(IND_NR);
                tx_modelo.setText(IND_NR);
               
           }catch(Exception e){
               System.out.println("error al grabar "+e.getMessage());
           }
    }//GEN-LAST:event_bn_editarclienteActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tx_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_nombreActionPerformed

    private void tx_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_marcaActionPerformed

    private void bn_buscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_buscarclienteActionPerformed
        String placa_el =jTextField1.getText();
        String script= String.format("select * from registro where placa='%s'",placa_el);
        TableModel tabla =registro.consultar(script).getModel();
        if((tabla != null)){
           tx_placa.setText(tabla.getValueAt(0, 0).toString());
           tx_nombre.setText(tabla.getValueAt(0, 1).toString());
           tx_residencia.setText(tabla.getValueAt(0, 2).toString());
           tx_celular.setText(tabla.getValueAt(0, 3).toString());
           tx_modelo.setText(tabla.getValueAt(0, 4).toString());
           tx_marca.setText(tabla.getValueAt(0, 5).toString());
            
        }else{
            JOptionPane.showMessageDialog(null, "no encontrado");
        }
            
    }//GEN-LAST:event_bn_buscarclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new editar_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn_buscarcliente;
    private javax.swing.JButton bn_editarcliente;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tx_celular;
    private javax.swing.JTextField tx_marca;
    private javax.swing.JTextField tx_modelo;
    private javax.swing.JTextField tx_nombre;
    private javax.swing.JTextField tx_placa;
    private javax.swing.JTextField tx_residencia;
    // End of variables declaration//GEN-END:variables
}
