/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_parqueadero;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author home
 */
public class Inicio extends javax.swing.JFrame {
   
    private final String EMPTY = new String () ;
    /**
     * Creates new form Inicio
     */
    Registro registro;
     public Inicio(Registro registro1) {
       registro = registro1;
        initComponents();
    } 
     Ubicacion ubicacion;
  public void resivir_ubicacion(Ubicacion ubicacion1){
      ubicacion = ubicacion1;
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane_principal = new javax.swing.JTabbedPane();
        jPanel_inicio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tx_placa = new javax.swing.JTextField();
        bn_registrar = new javax.swing.JButton();
        jPanel_primer = new javax.swing.JPanel();
        jButton_p1a3 = new javax.swing.JButton();
        jButton_p2a3 = new javax.swing.JButton();
        jButton_p3a3 = new javax.swing.JButton();
        jButton_p4a3 = new javax.swing.JButton();
        jButton_p5a3 = new javax.swing.JButton();
        jButton_p6a3 = new javax.swing.JButton();
        jButton_p7a3 = new javax.swing.JButton();
        jButton_p8a3 = new javax.swing.JButton();
        jButton_p9a2 = new javax.swing.JButton();
        jButton_p10a3 = new javax.swing.JButton();
        jButton_p11a3 = new javax.swing.JButton();
        jButton_p12a3 = new javax.swing.JButton();
        jButton_p13a3 = new javax.swing.JButton();
        jButton_p14a2 = new javax.swing.JButton();
        jButton_p15a3 = new javax.swing.JButton();
        jButton_p16a3 = new javax.swing.JButton();
        jButton_p17a3 = new javax.swing.JButton();
        jButton_p18a3 = new javax.swing.JButton();
        jButton_p19a3 = new javax.swing.JButton();
        jButton_p20a3 = new javax.swing.JButton();
        jButton_p21a3 = new javax.swing.JButton();
        jButton_p22a3 = new javax.swing.JButton();
        jButton_p23a3 = new javax.swing.JButton();
        jButton_p24a3 = new javax.swing.JButton();
        jButton_p25a3 = new javax.swing.JButton();
        jButton_p26a3 = new javax.swing.JButton();
        jButton_p27a3 = new javax.swing.JButton();
        jButton_p28a3 = new javax.swing.JButton();
        jButton_p29a3 = new javax.swing.JButton();
        jButton_p30a3 = new javax.swing.JButton();
        jButton_p31a3 = new javax.swing.JButton();
        jButton_p32a3 = new javax.swing.JButton();
        jButton_p33a3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel_segunda = new javax.swing.JPanel();
        jButton_p34a4 = new javax.swing.JButton();
        jButton_p35a4 = new javax.swing.JButton();
        jButton_p36a4 = new javax.swing.JButton();
        jButton_p37a4 = new javax.swing.JButton();
        jButton_p38a4 = new javax.swing.JButton();
        jButton_p39a4 = new javax.swing.JButton();
        jButton_p40a4 = new javax.swing.JButton();
        jButton_p41a4 = new javax.swing.JButton();
        jButton_p42a4 = new javax.swing.JButton();
        jButton_p43a4 = new javax.swing.JButton();
        jButton_p44a4 = new javax.swing.JButton();
        jButton_p45a4 = new javax.swing.JButton();
        jButton_p46a4 = new javax.swing.JButton();
        jButton_p47a4 = new javax.swing.JButton();
        jButton_p48a4 = new javax.swing.JButton();
        jButton_p49a4 = new javax.swing.JButton();
        jButton_p50a4 = new javax.swing.JButton();
        jButton_p51a4 = new javax.swing.JButton();
        jButton_p52a4 = new javax.swing.JButton();
        jButton_p53a4 = new javax.swing.JButton();
        jButton_p54a4 = new javax.swing.JButton();
        jButton_p55a4 = new javax.swing.JButton();
        jButton_p56a4 = new javax.swing.JButton();
        jButton_p57a4 = new javax.swing.JButton();
        jButton_p58a4 = new javax.swing.JButton();
        jButton_p59a4 = new javax.swing.JButton();
        jButton_p60a4 = new javax.swing.JButton();
        jButton_p61a4 = new javax.swing.JButton();
        jButton_p62a4 = new javax.swing.JButton();
        jButton_p63a4 = new javax.swing.JButton();
        jButton_p64a4 = new javax.swing.JButton();
        jButton_p65a4 = new javax.swing.JButton();
        jButton_p66a4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel_tercera = new javax.swing.JPanel();
        jButton_p67a2 = new javax.swing.JButton();
        jButton_p68a2 = new javax.swing.JButton();
        jButton_p69a2 = new javax.swing.JButton();
        jButton_p70a2 = new javax.swing.JButton();
        jButton_p71a2 = new javax.swing.JButton();
        jButton_p72a2 = new javax.swing.JButton();
        jButton_p73a2 = new javax.swing.JButton();
        jButton_p74a2 = new javax.swing.JButton();
        jButton_p75a2 = new javax.swing.JButton();
        jButton_p76a2 = new javax.swing.JButton();
        jButton_p77a2 = new javax.swing.JButton();
        jButton_p78a2 = new javax.swing.JButton();
        jButton_p79a2 = new javax.swing.JButton();
        jButton_p80a2 = new javax.swing.JButton();
        jButton_p81a2 = new javax.swing.JButton();
        jButton_p82a2 = new javax.swing.JButton();
        jButton_p83a2 = new javax.swing.JButton();
        jButton_p84a2 = new javax.swing.JButton();
        jButton_p85a2 = new javax.swing.JButton();
        jButton_p86a2 = new javax.swing.JButton();
        jButton_p87a2 = new javax.swing.JButton();
        jButton_p88a2 = new javax.swing.JButton();
        jButton_p89a2 = new javax.swing.JButton();
        jButton_p90a2 = new javax.swing.JButton();
        jButton_p91a2 = new javax.swing.JButton();
        jButton_p92a2 = new javax.swing.JButton();
        jButton_p93a2 = new javax.swing.JButton();
        jButton_p94a2 = new javax.swing.JButton();
        jButton_p95a2 = new javax.swing.JButton();
        jButton_p96a2 = new javax.swing.JButton();
        jButton_p97a2 = new javax.swing.JButton();
        jButton_p98a2 = new javax.swing.JButton();
        jButton_p99a2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("aplicativo de parqueadero");

        jTabbedPane_principal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane_principal.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel2.setText("INGRESE SU PLACA ");

        tx_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_placaActionPerformed(evt);
            }
        });

        bn_registrar.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        bn_registrar.setText("ACCEDER");
        bn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_inicioLayout = new javax.swing.GroupLayout(jPanel_inicio);
        jPanel_inicio.setLayout(jPanel_inicioLayout);
        jPanel_inicioLayout.setHorizontalGroup(
            jPanel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_inicioLayout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addGroup(jPanel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel_inicioLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(tx_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_inicioLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(bn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(269, 269, 269))
        );
        jPanel_inicioLayout.setVerticalGroup(
            jPanel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inicioLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tx_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        jTabbedPane_principal.addTab("inicio", jPanel_inicio);

        jPanel_primer.setBackground(new java.awt.Color(102, 102, 102));
        jPanel_primer.setMaximumSize(new java.awt.Dimension(801, 471));
        jPanel_primer.setMinimumSize(new java.awt.Dimension(801, 471));
        jPanel_primer.setLayout(null);

        jButton_p1a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p1a3.setText("1");
        jButton_p1a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p1a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p1a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p1a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p1a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p1a3);
        jButton_p1a3.setBounds(100, 130, 50, 40);

        jButton_p2a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p2a3.setText("2");
        jButton_p2a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p2a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p2a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p2a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p2a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p2a3);
        jButton_p2a3.setBounds(150, 130, 50, 40);

        jButton_p3a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p3a3.setText("3");
        jButton_p3a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p3a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p3a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p3a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p3a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p3a3);
        jButton_p3a3.setBounds(200, 130, 50, 40);

        jButton_p4a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p4a3.setText("4");
        jButton_p4a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p4a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p4a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p4a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p4a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p4a3);
        jButton_p4a3.setBounds(250, 130, 50, 40);

        jButton_p5a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p5a3.setText("5");
        jButton_p5a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p5a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p5a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p5a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p5a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p5a3);
        jButton_p5a3.setBounds(300, 130, 50, 40);

        jButton_p6a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p6a3.setText("6");
        jButton_p6a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p6a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p6a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p6a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p6a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p6a3);
        jButton_p6a3.setBounds(350, 130, 50, 40);

        jButton_p7a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p7a3.setText("7");
        jButton_p7a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p7a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p7a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p7a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p7a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p7a3);
        jButton_p7a3.setBounds(400, 130, 50, 40);

        jButton_p8a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p8a3.setText("8");
        jButton_p8a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p8a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p8a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p8a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p8a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p8a3);
        jButton_p8a3.setBounds(450, 130, 50, 40);

        jButton_p9a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p9a2.setText("9");
        jButton_p9a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p9a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p9a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p9a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p9a2ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p9a2);
        jButton_p9a2.setBounds(500, 130, 50, 40);

        jButton_p10a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p10a3.setText("10");
        jButton_p10a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p10a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p10a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p10a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p10a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p10a3);
        jButton_p10a3.setBounds(550, 130, 50, 40);

        jButton_p11a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p11a3.setText("11");
        jButton_p11a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p11a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p11a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p11a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p11a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p11a3);
        jButton_p11a3.setBounds(600, 130, 50, 40);

        jButton_p12a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p12a3.setText("12");
        jButton_p12a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p12a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p12a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p12a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p12a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p12a3);
        jButton_p12a3.setBounds(650, 130, 50, 40);

        jButton_p13a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p13a3.setText("13");
        jButton_p13a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p13a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p13a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p13a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p13a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p13a3);
        jButton_p13a3.setBounds(100, 170, 50, 40);

        jButton_p14a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p14a2.setText("14");
        jButton_p14a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p14a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p14a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p14a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p14a2ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p14a2);
        jButton_p14a2.setBounds(150, 170, 50, 40);

        jButton_p15a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p15a3.setText("15");
        jButton_p15a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p15a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p15a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p15a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p15a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p15a3);
        jButton_p15a3.setBounds(200, 170, 50, 40);

        jButton_p16a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p16a3.setText("16");
        jButton_p16a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p16a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p16a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p16a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p16a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p16a3);
        jButton_p16a3.setBounds(250, 170, 50, 40);

        jButton_p17a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p17a3.setText("17");
        jButton_p17a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p17a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p17a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p17a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p17a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p17a3);
        jButton_p17a3.setBounds(300, 170, 50, 40);

        jButton_p18a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p18a3.setText("18");
        jButton_p18a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p18a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p18a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p18a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p18a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p18a3);
        jButton_p18a3.setBounds(350, 170, 50, 40);

        jButton_p19a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p19a3.setText("19");
        jButton_p19a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p19a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p19a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p19a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p19a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p19a3);
        jButton_p19a3.setBounds(400, 170, 50, 40);

        jButton_p20a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p20a3.setText("20");
        jButton_p20a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p20a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p20a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p20a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p20a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p20a3);
        jButton_p20a3.setBounds(450, 170, 50, 40);

        jButton_p21a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p21a3.setText("21");
        jButton_p21a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p21a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p21a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p21a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p21a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p21a3);
        jButton_p21a3.setBounds(500, 170, 50, 40);

        jButton_p22a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p22a3.setText("22");
        jButton_p22a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p22a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p22a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p22a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p22a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p22a3);
        jButton_p22a3.setBounds(550, 170, 50, 40);

        jButton_p23a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p23a3.setText("23");
        jButton_p23a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p23a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p23a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p23a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p23a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p23a3);
        jButton_p23a3.setBounds(600, 170, 50, 40);

        jButton_p24a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p24a3.setText("24");
        jButton_p24a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p24a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p24a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p24a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p24a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p24a3);
        jButton_p24a3.setBounds(650, 170, 50, 40);

        jButton_p25a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p25a3.setText("25");
        jButton_p25a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p25a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p25a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p25a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p25a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p25a3);
        jButton_p25a3.setBounds(100, 210, 50, 40);

        jButton_p26a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p26a3.setText("26");
        jButton_p26a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p26a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p26a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p26a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p26a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p26a3);
        jButton_p26a3.setBounds(150, 210, 50, 40);

        jButton_p27a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p27a3.setText("27");
        jButton_p27a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p27a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p27a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p27a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p27a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p27a3);
        jButton_p27a3.setBounds(200, 210, 50, 40);

        jButton_p28a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p28a3.setText("28");
        jButton_p28a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p28a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p28a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_primer.add(jButton_p28a3);
        jButton_p28a3.setBounds(250, 210, 50, 40);

        jButton_p29a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p29a3.setText("29");
        jButton_p29a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p29a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p29a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_primer.add(jButton_p29a3);
        jButton_p29a3.setBounds(300, 210, 50, 40);

        jButton_p30a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p30a3.setText("30");
        jButton_p30a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p30a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p30a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p30a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p30a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p30a3);
        jButton_p30a3.setBounds(350, 210, 50, 40);

        jButton_p31a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p31a3.setText("31");
        jButton_p31a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p31a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p31a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p31a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p31a3ActionPerformed(evt);
            }
        });
        jPanel_primer.add(jButton_p31a3);
        jButton_p31a3.setBounds(400, 210, 50, 40);

        jButton_p32a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p32a3.setText("32");
        jButton_p32a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p32a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p32a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_primer.add(jButton_p32a3);
        jButton_p32a3.setBounds(450, 210, 50, 40);

        jButton_p33a3.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p33a3.setText("33");
        jButton_p33a3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p33a3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p33a3.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_primer.add(jButton_p33a3);
        jButton_p33a3.setBounds(500, 210, 50, 40);

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel4.setText("seleccione la posicion de ubicacion");
        jPanel_primer.add(jLabel4);
        jLabel4.setBounds(170, 30, 460, 70);

        jTabbedPane_principal.addTab("primer planta", jPanel_primer);

        jPanel_segunda.setBackground(new java.awt.Color(102, 102, 102));
        jPanel_segunda.setMaximumSize(new java.awt.Dimension(801, 529));
        jPanel_segunda.setMinimumSize(new java.awt.Dimension(801, 529));
        jPanel_segunda.setLayout(null);

        jButton_p34a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p34a4.setText("34");
        jButton_p34a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p34a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p34a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p34a4);
        jButton_p34a4.setBounds(550, 110, 50, 40);

        jButton_p35a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p35a4.setText("35");
        jButton_p35a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p35a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p35a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p35a4);
        jButton_p35a4.setBounds(600, 110, 50, 40);

        jButton_p36a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p36a4.setText("36");
        jButton_p36a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p36a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p36a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p36a4);
        jButton_p36a4.setBounds(650, 110, 50, 40);

        jButton_p37a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p37a4.setText("37");
        jButton_p37a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p37a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p37a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p37a4);
        jButton_p37a4.setBounds(100, 150, 50, 40);

        jButton_p38a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p38a4.setText("38");
        jButton_p38a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p38a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p38a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p38a4);
        jButton_p38a4.setBounds(150, 150, 50, 40);

        jButton_p39a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p39a4.setText("39");
        jButton_p39a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p39a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p39a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p39a4);
        jButton_p39a4.setBounds(200, 150, 50, 40);

        jButton_p40a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p40a4.setText("40");
        jButton_p40a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p40a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p40a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p40a4);
        jButton_p40a4.setBounds(250, 150, 50, 40);

        jButton_p41a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p41a4.setText("41");
        jButton_p41a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p41a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p41a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p41a4);
        jButton_p41a4.setBounds(300, 150, 50, 40);

        jButton_p42a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p42a4.setText("42");
        jButton_p42a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p42a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p42a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p42a4);
        jButton_p42a4.setBounds(350, 150, 50, 40);

        jButton_p43a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p43a4.setText("43");
        jButton_p43a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p43a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p43a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p43a4);
        jButton_p43a4.setBounds(400, 150, 50, 40);

        jButton_p44a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p44a4.setText("44");
        jButton_p44a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p44a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p44a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p44a4);
        jButton_p44a4.setBounds(450, 150, 50, 40);

        jButton_p45a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p45a4.setText("45");
        jButton_p45a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p45a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p45a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p45a4);
        jButton_p45a4.setBounds(500, 150, 50, 40);

        jButton_p46a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p46a4.setText("46");
        jButton_p46a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p46a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p46a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p46a4);
        jButton_p46a4.setBounds(550, 150, 50, 40);

        jButton_p47a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p47a4.setText("47");
        jButton_p47a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p47a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p47a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p47a4);
        jButton_p47a4.setBounds(600, 150, 50, 40);

        jButton_p48a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p48a4.setText("48");
        jButton_p48a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p48a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p48a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p48a4);
        jButton_p48a4.setBounds(650, 150, 50, 40);

        jButton_p49a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p49a4.setText("49");
        jButton_p49a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p49a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p49a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p49a4);
        jButton_p49a4.setBounds(100, 190, 50, 40);

        jButton_p50a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p50a4.setText("50");
        jButton_p50a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p50a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p50a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p50a4);
        jButton_p50a4.setBounds(150, 190, 50, 40);

        jButton_p51a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p51a4.setText("51");
        jButton_p51a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p51a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p51a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p51a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p51a4ActionPerformed(evt);
            }
        });
        jPanel_segunda.add(jButton_p51a4);
        jButton_p51a4.setBounds(200, 190, 50, 40);

        jButton_p52a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p52a4.setText("52");
        jButton_p52a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p52a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p52a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p52a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p52a4ActionPerformed(evt);
            }
        });
        jPanel_segunda.add(jButton_p52a4);
        jButton_p52a4.setBounds(250, 190, 50, 40);

        jButton_p53a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p53a4.setText("53");
        jButton_p53a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p53a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p53a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p53a4);
        jButton_p53a4.setBounds(300, 190, 50, 40);

        jButton_p54a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p54a4.setText("54");
        jButton_p54a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p54a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p54a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p54a4);
        jButton_p54a4.setBounds(350, 190, 50, 40);

        jButton_p55a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p55a4.setText("55");
        jButton_p55a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p55a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p55a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p55a4);
        jButton_p55a4.setBounds(400, 190, 50, 40);

        jButton_p56a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p56a4.setText("56");
        jButton_p56a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p56a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p56a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p56a4);
        jButton_p56a4.setBounds(450, 190, 50, 40);

        jButton_p57a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p57a4.setText("57");
        jButton_p57a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p57a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p57a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p57a4);
        jButton_p57a4.setBounds(500, 190, 50, 40);

        jButton_p58a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p58a4.setText("58");
        jButton_p58a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p58a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p58a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p58a4);
        jButton_p58a4.setBounds(550, 190, 50, 40);

        jButton_p59a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p59a4.setText("59");
        jButton_p59a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p59a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p59a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p59a4);
        jButton_p59a4.setBounds(600, 190, 50, 40);

        jButton_p60a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p60a4.setText("60");
        jButton_p60a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p60a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p60a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p60a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p60a4ActionPerformed(evt);
            }
        });
        jPanel_segunda.add(jButton_p60a4);
        jButton_p60a4.setBounds(650, 190, 50, 40);

        jButton_p61a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p61a4.setText("61");
        jButton_p61a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p61a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p61a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p61a4);
        jButton_p61a4.setBounds(100, 230, 50, 40);

        jButton_p62a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p62a4.setText("62");
        jButton_p62a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p62a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p62a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p62a4);
        jButton_p62a4.setBounds(150, 230, 50, 40);

        jButton_p63a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p63a4.setText("63");
        jButton_p63a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p63a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p63a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p63a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p63a4ActionPerformed(evt);
            }
        });
        jPanel_segunda.add(jButton_p63a4);
        jButton_p63a4.setBounds(200, 230, 50, 40);

        jButton_p64a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p64a4.setText("64");
        jButton_p64a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p64a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p64a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p64a4);
        jButton_p64a4.setBounds(250, 230, 50, 40);

        jButton_p65a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p65a4.setText("65");
        jButton_p65a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p65a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p65a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p65a4);
        jButton_p65a4.setBounds(300, 230, 50, 40);

        jButton_p66a4.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p66a4.setText("66");
        jButton_p66a4.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p66a4.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p66a4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_segunda.add(jButton_p66a4);
        jButton_p66a4.setBounds(350, 230, 50, 40);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel5.setText("seleccione la posicion de ubicacion");
        jPanel_segunda.add(jLabel5);
        jLabel5.setBounds(170, 30, 460, 70);

        jTabbedPane_principal.addTab("segunda planta", jPanel_segunda);

        jPanel_tercera.setBackground(new java.awt.Color(102, 102, 102));
        jPanel_tercera.setLayout(null);

        jButton_p67a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p67a2.setText("67");
        jButton_p67a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p67a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p67a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p67a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p67a2ActionPerformed(evt);
            }
        });
        jPanel_tercera.add(jButton_p67a2);
        jButton_p67a2.setBounds(400, 130, 50, 40);

        jButton_p68a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p68a2.setText("68");
        jButton_p68a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p68a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p68a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p68a2);
        jButton_p68a2.setBounds(450, 130, 50, 40);

        jButton_p69a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p69a2.setText("69");
        jButton_p69a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p69a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p69a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p69a2);
        jButton_p69a2.setBounds(500, 130, 50, 40);

        jButton_p70a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p70a2.setText("70");
        jButton_p70a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p70a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p70a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p70a2);
        jButton_p70a2.setBounds(550, 130, 50, 40);

        jButton_p71a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p71a2.setText("71");
        jButton_p71a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p71a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p71a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p71a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p71a2ActionPerformed(evt);
            }
        });
        jPanel_tercera.add(jButton_p71a2);
        jButton_p71a2.setBounds(600, 130, 50, 40);

        jButton_p72a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p72a2.setText("72");
        jButton_p72a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p72a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p72a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p72a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p72a2ActionPerformed(evt);
            }
        });
        jPanel_tercera.add(jButton_p72a2);
        jButton_p72a2.setBounds(650, 130, 50, 40);

        jButton_p73a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p73a2.setText("73");
        jButton_p73a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p73a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p73a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p73a2);
        jButton_p73a2.setBounds(100, 170, 50, 40);

        jButton_p74a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p74a2.setText("74");
        jButton_p74a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p74a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p74a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p74a2);
        jButton_p74a2.setBounds(150, 170, 50, 40);

        jButton_p75a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p75a2.setText("75");
        jButton_p75a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p75a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p75a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p75a2);
        jButton_p75a2.setBounds(200, 170, 50, 40);

        jButton_p76a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p76a2.setText("76");
        jButton_p76a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p76a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p76a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p76a2);
        jButton_p76a2.setBounds(250, 170, 50, 40);

        jButton_p77a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p77a2.setText("77");
        jButton_p77a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p77a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p77a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p77a2);
        jButton_p77a2.setBounds(300, 170, 50, 40);

        jButton_p78a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p78a2.setText("78");
        jButton_p78a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p78a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p78a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p78a2);
        jButton_p78a2.setBounds(350, 170, 50, 40);

        jButton_p79a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p79a2.setText("79");
        jButton_p79a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p79a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p79a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p79a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p79a2ActionPerformed(evt);
            }
        });
        jPanel_tercera.add(jButton_p79a2);
        jButton_p79a2.setBounds(400, 170, 50, 40);

        jButton_p80a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p80a2.setText("80");
        jButton_p80a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p80a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p80a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p80a2);
        jButton_p80a2.setBounds(450, 170, 50, 40);

        jButton_p81a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p81a2.setText("81");
        jButton_p81a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p81a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p81a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p81a2);
        jButton_p81a2.setBounds(500, 170, 50, 40);

        jButton_p82a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p82a2.setText("82");
        jButton_p82a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p82a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p82a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p82a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p82a2ActionPerformed(evt);
            }
        });
        jPanel_tercera.add(jButton_p82a2);
        jButton_p82a2.setBounds(550, 170, 50, 40);

        jButton_p83a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p83a2.setText("83");
        jButton_p83a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p83a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p83a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p83a2);
        jButton_p83a2.setBounds(600, 170, 50, 40);

        jButton_p84a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p84a2.setText("84");
        jButton_p84a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p84a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p84a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p84a2);
        jButton_p84a2.setBounds(650, 170, 50, 40);

        jButton_p85a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p85a2.setText("85");
        jButton_p85a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p85a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p85a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p85a2);
        jButton_p85a2.setBounds(100, 210, 50, 40);

        jButton_p86a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p86a2.setText("86");
        jButton_p86a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p86a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p86a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p86a2);
        jButton_p86a2.setBounds(150, 210, 50, 40);

        jButton_p87a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p87a2.setText("87");
        jButton_p87a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p87a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p87a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p87a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p87a2ActionPerformed(evt);
            }
        });
        jPanel_tercera.add(jButton_p87a2);
        jButton_p87a2.setBounds(200, 210, 50, 40);

        jButton_p88a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p88a2.setText("88");
        jButton_p88a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p88a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p88a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p88a2);
        jButton_p88a2.setBounds(250, 210, 50, 40);

        jButton_p89a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p89a2.setText("89");
        jButton_p89a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p89a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p89a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p89a2);
        jButton_p89a2.setBounds(300, 210, 50, 40);

        jButton_p90a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p90a2.setText("90");
        jButton_p90a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p90a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p90a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p90a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p90a2ActionPerformed(evt);
            }
        });
        jPanel_tercera.add(jButton_p90a2);
        jButton_p90a2.setBounds(350, 210, 50, 40);

        jButton_p91a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p91a2.setText("91");
        jButton_p91a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p91a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p91a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p91a2);
        jButton_p91a2.setBounds(400, 210, 50, 40);

        jButton_p92a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p92a2.setText("92");
        jButton_p92a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p92a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p92a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p92a2);
        jButton_p92a2.setBounds(450, 210, 50, 40);

        jButton_p93a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p93a2.setText("93");
        jButton_p93a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p93a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p93a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p93a2);
        jButton_p93a2.setBounds(500, 210, 50, 40);

        jButton_p94a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p94a2.setText("94");
        jButton_p94a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p94a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p94a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p94a2);
        jButton_p94a2.setBounds(550, 210, 50, 40);

        jButton_p95a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p95a2.setText("95");
        jButton_p95a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p95a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p95a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p95a2);
        jButton_p95a2.setBounds(600, 210, 50, 40);

        jButton_p96a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p96a2.setText("96");
        jButton_p96a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p96a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p96a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p96a2);
        jButton_p96a2.setBounds(650, 210, 50, 40);

        jButton_p97a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p97a2.setText("97");
        jButton_p97a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p97a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p97a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p97a2);
        jButton_p97a2.setBounds(100, 250, 50, 40);

        jButton_p98a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p98a2.setText("98");
        jButton_p98a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p98a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p98a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel_tercera.add(jButton_p98a2);
        jButton_p98a2.setBounds(150, 250, 50, 40);

        jButton_p99a2.setBackground(new java.awt.Color(204, 255, 255));
        jButton_p99a2.setText("99");
        jButton_p99a2.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton_p99a2.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton_p99a2.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton_p99a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_p99a2ActionPerformed(evt);
            }
        });
        jPanel_tercera.add(jButton_p99a2);
        jButton_p99a2.setBounds(200, 250, 50, 40);

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel6.setText("seleccione la posicion de ubicacion");
        jPanel_tercera.add(jLabel6);
        jLabel6.setBounds(170, 30, 460, 70);

        jTabbedPane_principal.addTab("tercera planta", jPanel_tercera);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setText("CONTROL DE PARQUEADERO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jTabbedPane_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_placaActionPerformed

    private void bn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_registrarActionPerformed
    
        if(EMPTY.equals(tx_placa.getText().trim())){
            JOptionPane.showMessageDialog(null, "ingrese la placa");
        }else{
            ubicacion.setVisible(true);
            ubicacion.placa_res(tx_placa.getText());
            ubicacion.desactivar();
        }
    
    
    }//GEN-LAST:event_bn_registrarActionPerformed

    private void jButton_p1a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p1a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p1a3ActionPerformed

    private void jButton_p2a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p2a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p2a3ActionPerformed

    private void jButton_p3a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p3a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p3a3ActionPerformed

    private void jButton_p4a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p4a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p4a3ActionPerformed

    private void jButton_p5a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p5a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p5a3ActionPerformed

    private void jButton_p6a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p6a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p6a3ActionPerformed

    private void jButton_p7a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p7a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p7a3ActionPerformed

    private void jButton_p8a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p8a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p8a3ActionPerformed

    private void jButton_p9a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p9a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p9a2ActionPerformed

    private void jButton_p10a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p10a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p10a3ActionPerformed

    private void jButton_p11a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p11a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p11a3ActionPerformed

    private void jButton_p12a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p12a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p12a3ActionPerformed

    private void jButton_p13a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p13a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p13a3ActionPerformed

    private void jButton_p14a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p14a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p14a2ActionPerformed

    private void jButton_p15a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p15a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p15a3ActionPerformed

    private void jButton_p16a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p16a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p16a3ActionPerformed

    private void jButton_p17a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p17a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p17a3ActionPerformed

    private void jButton_p18a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p18a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p18a3ActionPerformed

    private void jButton_p19a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p19a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p19a3ActionPerformed

    private void jButton_p20a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p20a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p20a3ActionPerformed

    private void jButton_p21a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p21a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p21a3ActionPerformed

    private void jButton_p22a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p22a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p22a3ActionPerformed

    private void jButton_p23a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p23a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p23a3ActionPerformed

    private void jButton_p24a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p24a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p24a3ActionPerformed

    private void jButton_p25a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p25a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p25a3ActionPerformed

    private void jButton_p26a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p26a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p26a3ActionPerformed

    private void jButton_p27a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p27a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p27a3ActionPerformed

    private void jButton_p30a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p30a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p30a3ActionPerformed

    private void jButton_p31a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p31a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p31a3ActionPerformed

    private void jButton_p51a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p51a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p51a4ActionPerformed

    private void jButton_p52a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p52a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p52a4ActionPerformed

    private void jButton_p60a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p60a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p60a4ActionPerformed

    private void jButton_p63a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p63a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p63a4ActionPerformed

    private void jButton_p99a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p99a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p99a2ActionPerformed

    private void jButton_p90a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p90a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p90a2ActionPerformed

    private void jButton_p87a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p87a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p87a2ActionPerformed

    private void jButton_p82a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p82a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p82a2ActionPerformed

    private void jButton_p79a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p79a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p79a2ActionPerformed

    private void jButton_p72a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p72a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p72a2ActionPerformed

    private void jButton_p71a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p71a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p71a2ActionPerformed

    private void jButton_p67a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_p67a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_p67a2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn_registrar;
    private javax.swing.JButton jButton_p10a3;
    private javax.swing.JButton jButton_p11a3;
    private javax.swing.JButton jButton_p12a3;
    private javax.swing.JButton jButton_p13a3;
    private javax.swing.JButton jButton_p14a2;
    private javax.swing.JButton jButton_p15a3;
    private javax.swing.JButton jButton_p16a3;
    private javax.swing.JButton jButton_p17a3;
    private javax.swing.JButton jButton_p18a3;
    private javax.swing.JButton jButton_p19a3;
    private javax.swing.JButton jButton_p1a3;
    private javax.swing.JButton jButton_p20a3;
    private javax.swing.JButton jButton_p21a3;
    private javax.swing.JButton jButton_p22a3;
    private javax.swing.JButton jButton_p23a3;
    private javax.swing.JButton jButton_p24a3;
    private javax.swing.JButton jButton_p25a3;
    private javax.swing.JButton jButton_p26a3;
    private javax.swing.JButton jButton_p27a3;
    private javax.swing.JButton jButton_p28a3;
    private javax.swing.JButton jButton_p29a3;
    private javax.swing.JButton jButton_p2a3;
    private javax.swing.JButton jButton_p30a3;
    private javax.swing.JButton jButton_p31a3;
    private javax.swing.JButton jButton_p32a3;
    private javax.swing.JButton jButton_p33a3;
    private javax.swing.JButton jButton_p34a4;
    private javax.swing.JButton jButton_p35a4;
    private javax.swing.JButton jButton_p36a4;
    private javax.swing.JButton jButton_p37a4;
    private javax.swing.JButton jButton_p38a4;
    private javax.swing.JButton jButton_p39a4;
    private javax.swing.JButton jButton_p3a3;
    private javax.swing.JButton jButton_p40a4;
    private javax.swing.JButton jButton_p41a4;
    private javax.swing.JButton jButton_p42a4;
    private javax.swing.JButton jButton_p43a4;
    private javax.swing.JButton jButton_p44a4;
    private javax.swing.JButton jButton_p45a4;
    private javax.swing.JButton jButton_p46a4;
    private javax.swing.JButton jButton_p47a4;
    private javax.swing.JButton jButton_p48a4;
    private javax.swing.JButton jButton_p49a4;
    private javax.swing.JButton jButton_p4a3;
    private javax.swing.JButton jButton_p50a4;
    private javax.swing.JButton jButton_p51a4;
    private javax.swing.JButton jButton_p52a4;
    private javax.swing.JButton jButton_p53a4;
    private javax.swing.JButton jButton_p54a4;
    private javax.swing.JButton jButton_p55a4;
    private javax.swing.JButton jButton_p56a4;
    private javax.swing.JButton jButton_p57a4;
    private javax.swing.JButton jButton_p58a4;
    private javax.swing.JButton jButton_p59a4;
    private javax.swing.JButton jButton_p5a3;
    private javax.swing.JButton jButton_p60a4;
    private javax.swing.JButton jButton_p61a4;
    private javax.swing.JButton jButton_p62a4;
    private javax.swing.JButton jButton_p63a4;
    private javax.swing.JButton jButton_p64a4;
    private javax.swing.JButton jButton_p65a4;
    private javax.swing.JButton jButton_p66a4;
    private javax.swing.JButton jButton_p67a2;
    private javax.swing.JButton jButton_p68a2;
    private javax.swing.JButton jButton_p69a2;
    private javax.swing.JButton jButton_p6a3;
    private javax.swing.JButton jButton_p70a2;
    private javax.swing.JButton jButton_p71a2;
    private javax.swing.JButton jButton_p72a2;
    private javax.swing.JButton jButton_p73a2;
    private javax.swing.JButton jButton_p74a2;
    private javax.swing.JButton jButton_p75a2;
    private javax.swing.JButton jButton_p76a2;
    private javax.swing.JButton jButton_p77a2;
    private javax.swing.JButton jButton_p78a2;
    private javax.swing.JButton jButton_p79a2;
    private javax.swing.JButton jButton_p7a3;
    private javax.swing.JButton jButton_p80a2;
    private javax.swing.JButton jButton_p81a2;
    private javax.swing.JButton jButton_p82a2;
    private javax.swing.JButton jButton_p83a2;
    private javax.swing.JButton jButton_p84a2;
    private javax.swing.JButton jButton_p85a2;
    private javax.swing.JButton jButton_p86a2;
    private javax.swing.JButton jButton_p87a2;
    private javax.swing.JButton jButton_p88a2;
    private javax.swing.JButton jButton_p89a2;
    private javax.swing.JButton jButton_p8a3;
    private javax.swing.JButton jButton_p90a2;
    private javax.swing.JButton jButton_p91a2;
    private javax.swing.JButton jButton_p92a2;
    private javax.swing.JButton jButton_p93a2;
    private javax.swing.JButton jButton_p94a2;
    private javax.swing.JButton jButton_p95a2;
    private javax.swing.JButton jButton_p96a2;
    private javax.swing.JButton jButton_p97a2;
    private javax.swing.JButton jButton_p98a2;
    private javax.swing.JButton jButton_p99a2;
    private javax.swing.JButton jButton_p9a2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_inicio;
    private javax.swing.JPanel jPanel_primer;
    private javax.swing.JPanel jPanel_segunda;
    private javax.swing.JPanel jPanel_tercera;
    private javax.swing.JTabbedPane jTabbedPane_principal;
    private javax.swing.JTextField tx_placa;
    // End of variables declaration//GEN-END:variables
}
